// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(VehicleDatabaseContext))]
    partial class VehicleDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.ENTITIES.Models.Boat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Color = 4,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6793),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Azure",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            Color = 3,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6797),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bavaria ",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            Color = 2,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6798),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jeanneau",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            Color = 3,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6799),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J Boats",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            Color = 1,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6801),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nautorswan",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            Color = 4,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6804),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Salona",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Bus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Color = 4,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6733),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Neoplan",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            Color = 2,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6736),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Man",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            Color = 1,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6738),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tourismo",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            Color = 3,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6739),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Travego",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            Color = 2,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6740),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maraton",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            Color = 1,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6743),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Safir",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HeadLight")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<byte?>("Wheels")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Color = 1,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6575),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BMW 320i",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 2,
                            Color = 1,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6589),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Citroen C3",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 3,
                            Color = 4,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6591),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dacia Logan",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 4,
                            Color = 4,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6592),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fiat Egea",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 5,
                            Color = 4,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6594),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ford Focus",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 6,
                            Color = 3,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6599),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Honda Civic",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 7,
                            Color = 2,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6601),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mercedes CLA",
                            Status = 1,
                            Wheels = (byte)4
                        },
                        new
                        {
                            ID = 8,
                            Color = 2,
                            CreatedDate = new DateTime(2024, 8, 22, 8, 35, 14, 557, DateTimeKind.Utc).AddTicks(6602),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadLight = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Opel Corsa",
                            Status = 1,
                            Wheels = (byte)4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
